### ISSUE TITLE
Non-Emulative Lexer defines tokenizer constants of future PHP versions

### ISSUE THREAD

**Issue by sebastianbergmann** [nikic/PHP-Parser#701]
The method `defineCompatibilityTokens()` of `PhpParser\Lexer` conditionally defines the `T_BAD_CHARACTER`, `T_FN`, `T_COALESCE_EQUAL`, `T_NAME_QUALIFIED`, `T_NAME_FULLY_QUALIFIED`, `T_NAME_RELATIVE`, `T_MATCH`, and `T_NULLSAFE_OBJECT_OPERATOR` when they are not already defined.

Why does the non-emulative lexer need these constants? This is something I would expect only `PhpParser\Lexer\Emulative` to need.

As of PHPUnit 9.3 (and php-code-coverage 9.0), PHPUnit uses PHP-Parser for static analysis of covered files when code coverage is used. As explained in https://github.com/sebastianbergmann/php-code-coverage/issues/798, the fact that `PhpParser\Lexer::defineCompatibilityTokens()` defines tokenizer constants that are not provided by the version of PHP used to run the tests interferes with the testing of backward/forward compatibility layers for tokenizer constants of software that uses the tokenizer extension.

**Comment by jrfnl** [comment]
@nikic Thanks for the reply.

That would effectively mean that any other project which works with tokens and/or backfills tokens and/or emulates tokens will no longer be able to use PHPUnit to generate code coverage as either the tests will fail if the PHP-Parser kicks in when the token is expected to not exist or if the project backfills the tokens before PHP-Parser does, code coverage will fail to generate correctly as the constants will no be declared to have the same value (i.e the value you'd expect for PHP-Parser).

I'm running into this currently when generating code coverage for several PHP_CodeSniffer related projects.

**Comment by nikic** [comment]
PHP-Parser does not care about the value of the tokens, just that they are defined and distinct from other tokens. It's okay if they get defined by some other library that also needs to polyfill tokens.

I would recommend to not depend on token existence to make any decisions (beyond whether to polyfill the constants yourself), and check the PHP version instead.

**Comment by jrfnl** [comment]
> I would recommend to not depend on token existence to make any decisions (beyond whether to polyfill the constants yourself), and check the PHP version instead.

Except we can't as more recent PHPCS will backfill the tokens, but older PHPCS version will not and both PHPCSUtils as well as PHPCompatibility support a wide range of PHPCS versions (for reasons), so we *need* to check whether the token is `defined()`. That's the whole point.

**Comment by jrfnl** [comment]
Oh and also, if the token is defined by `PHP-Parser`, we cannot use the `constant()` function anymore either as it will come back with an value which won't be recognized and results in an `UNKNOWN`.

**Comment by nikic** [comment]
Is there still an active interest in fixing this? I could probably do it in the next major version, but wouldn't bother if people have already worked around this anyway.

**Comment by sebastianbergmann** [comment]
Not by me, I think.

**Comment by harikagujjula** [comment]
I m facing this with PHP 8.1. Is there a plan on fixing this ?

**Comment by nikic** [comment]
> I m facing this with PHP 8.1. Is there a plan on fixing this ?

Could you please explain in more detail what problem you are seeing and in what context? (E.g. which library does compat token definition conflict with?)

**Comment by harikagujjula** [comment]
Sure. 

Running PHP compatibility check is resulting in the following errors on my project.

Command:  ./vendor/bin/phpcs -p vendor/nikic --standard=PHPCompatibility --runtime-set testVersion 8.1

46 | ERROR | The constant "T_BAD_CHARACTER" is removed since PHP 7.0
109 | ERROR | The constant "T_BAD_CHARACTER" is removed since PHP 7.0
151 | ERROR | The constant "T_BAD_CHARACTER" is removed since PHP 7.0

Using phpcs - 3.7.1, phpcompatibility - 9.3.5 (latest versions available).

**Comment by nikic** [comment]
Thanks! This sounds like a bug in PHPCompatibilty to me: While the T_BAD_CHARACTER constant was indeed removed in PHP 7.0, it was added back in PHP 7.4, so if you are checking for PHP 8.1 compatibility (I assume that's what the `--runtime-set testVersion 8.1` bit means), then this constant should not be reported as "removed".

**Comment by harikagujjula** [comment]
Yes, you are correct. `--runtime-set testVersion 8.1` indicates, checking for 8.1 compatibility. Thanks for your quick insights. I will follow up on PHPCompatibilty.

**Comment by jrfnl** [comment]
@harikagujjula I'm fairly certain that was fixed already in PHPCompatibility, but will double-check.

**Comment by harikagujjula** [comment]
I have tried to check with develop version too(versions : * 10.x-dev, * dev-develop), but was still seeing it. So, i have created a new issue https://github.com/PHPCompatibility/PHPCompatibility/issues/1351 

Please let me know if i am missing something or need any other information here.

Thanks.

**Comment by jrfnl** [comment]
> I have tried to check with develop version too(versions : * 10.x-dev, * dev-develop), but was still seeing it. So, i have created a new issue [PHPCompatibility/PHPCompatibility#1351](https://github.com/PHPCompatibility/PHPCompatibility/issues/1351)

I'll have a look over the next few days.

**Comment by harikagujjula** [comment]
Sure, Thanks.

**Comment by nikic** [comment]
Closing this as won't fix.
